-- MySQL Script generated by MySQL Workbench
-- 04/14/17 11:08:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema food_delivery
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `food_delivery` ;

-- -----------------------------------------------------
-- Schema food_delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_delivery` DEFAULT CHARACTER SET utf8 ;
USE `food_delivery` ;

-- -----------------------------------------------------
-- Table `food_delivery`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_delivery`.`dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`dish` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `weight` INT(11) NOT NULL,
  `price` DECIMAL(20,0) NOT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dish_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_dish_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `food_delivery`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_delivery`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_admin` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_delivery`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `food_delivery`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_delivery`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`user_info` (
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_info_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_info_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `food_delivery`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_delivery`.`dish_has_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`dish_has_order` (
  `dish_id` INT(11) NOT NULL,
  `order_id` INT(11) NOT NULL,
  `amount` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`dish_id`, `order_id`),
  INDEX `fk_dish_has_order_order1_idx` (`order_id` ASC),
  INDEX `fk_dish_has_order_dish1_idx` (`dish_id` ASC),
  CONSTRAINT `fk_dish_has_order_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `food_delivery`.`dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dish_has_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `food_delivery`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_delivery`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`subscription` (
  `category_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`category_id`, `user_id`),
  INDEX `fk_category_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_category_has_user_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_category_has_user_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `food_delivery`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `food_delivery`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
