-- MySQL Script generated by MySQL Workbench
-- Thu Apr 13 22:58:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema food_delivery
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `food_delivery` ;

-- -----------------------------------------------------
-- Schema food_delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_delivery` DEFAULT CHARACTER SET utf8 ;
USE `food_delivery` ;

-- -----------------------------------------------------
-- Table `food_delivery`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_admin` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`user_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_user_info_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_info_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `food_delivery`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `food_delivery`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`dish` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `weight` INT NOT NULL,
  `price` DECIMAL(20) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dish_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_dish_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `food_delivery`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `food_delivery`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`dishes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`dishes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `count` INT UNSIGNED NOT NULL,
  `dish_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dishes_dish1_idx` (`dish_id` ASC),
  INDEX `fk_dishes_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_dishes_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `food_delivery`.`dish` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dishes_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `food_delivery`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery`.`subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subscriptions_user1_idx` (`user_id` ASC),
  INDEX `fk_subscriptions_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_subscriptions_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `food_delivery`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_subscriptions_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `food_delivery`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
