# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Food Delivery' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'SVProgressHUD'
  pod 'Mantle'
  pod 'AFNetworking', '~> 3.0'
  pod 'RESideMenu'
  # Pods for Food Delivery

end
